set-option global makecmd 'make'
set-option global grepcmd 'ag --column'
set-option global ui_options 'ncurses_status_on_top=true' 'ncurses_assistant=none' 'ncurses_change_colors=false' 'ncurses_enable_mouse=false' 'ncurses_set_title=true'
# set-option global autoinfo normal|command|onkey

set-option global indentwidth 0

colorscheme tomorrow-night

add-highlighter global/ number-lines -hlcursor -separator ' '
add-highlighter global/ show-matching
# add-highlighter global/ show-whitespaces
add-highlighter global/ dynregex '%reg{/}' 0:+u
add-highlighter global/ wrap -word -indent

set-option global autocomplete prompt
hook global InsertBegin .* %{ map window insert <a-space> <c-o> }
hook global InsertEnd .* %{ unmap window insert <a-space> <c-o> }

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p>; execute-keys <c-o> }

map global normal '#' :comment-line<ret>

hook global WinSetOption filetype=(c|cpp) %{
	set-option global clang_options '-std=c++17'
	set-option global tabstop 4
	set-option window formatcmd '$CF -style=file'
# 	clang-enable-autocomplete
# 	clang-enable-diagnostics
# 	alias window lint clang-parse
# 	alias window lint-next-error clang-diagnostics-next
	set-option buffer matching_pairs '{' '}' '[' ']' '(' ')'

	try %{
		remove-highlighter buffer/operators
		add-highlighter buffer/operators regex (\W) 0:operator
		# remove-highlighter buffer/operators
		# add-highlighter    buffer/operators regex (\+|-|\*|&|=|\\|\?|%|\|-|!|\||->|\.|,|<|>|:|\^|/|~|\[|\]) 0:operator
	}
}

hook global ModuleLoaded c-family %{ try %{ evaluate-commands %sh{
	for filetype in c cpp; do
		printf "%s\n" "add-highlighter shared/$filetype/code/types_1 regex \b(v|u|vu)\w+(8|16|32|64)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_2 regex \b(v|u|vu)?(_|__)?(s|u)(8|16|32|64)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_3 regex \b(v|u|vu)(_|__)?(int|short|char|long)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_4 regex \b\w+_t\b 0:type"
	done
}}}

map global normal '<del>' :db<ret>
map global normal ';' :
# map global normal '<ret>' :make<ret>

# hook global BufCreate '^\*make\*$' %{
# 	hook -once buffer NormalKey '<del>' %{ try %{
# 		delete-buffer *make*
# 	}}
# }
