set-option global ui_options "terminal_status_on_top=%sh{ case $TERM in tmux*) echo true ;; *) echo false ;; esac }" 'terminal_assistant=none' 'terminal_change_colors=false' 'terminal_enable_mouse=false' 'terminal_set_title=true' "terminal_synchronized=%sh{ case $TERM in foot*) echo true ;; *) echo false ;; esac }"
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} of %val{buf_line_count}:? {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
# set-option global autoinfo normal|command|onkey
set-option global makecmd 'make'
set-option global grepcmd 'ag --nocolor --column'
set-option global indentwidth 0
set-option global tabstop 4
set-option global autocomplete prompt

# colorscheme tomorrow-night
colorscheme %sh{ case "$TERM" in xterm) echo "default" ;; *) echo "tomorrow-night" ;; esac }

add-highlighter global/ number-lines -hlcursor -separator ' '
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -tab '→' -spc '•' -lf ' ' -only-trailing
# add-highlighter global/ wrap -word -indent
# add-highlighter global/trailing-whitespace regex '\h+$' 0:Error

hook global -always BufOpenFifo '\*grep\*' %{ map global normal <minus> ': grep-next-match<ret>' }
hook global -always BufOpenFifo '\*make\*' %{ map global normal <minus> ': make-next-error<ret>' }

hook global ModeChange push:insert:.* %{ map window insert <a-space> <c-o> }
hook global ModeChange pop:insert:.* %{ unmap window insert <a-space> <c-o> }

hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p>; execute-keys <c-o> }

map global normal '#' :comment-line<ret>

# evaluate-commands %sh{
# 	if [ -n "$WAYLAND_DISPLAY" ]; then
# 		echo "map global normal p '<a-!>wl-paste -n<ret>'"
# 		echo "map global normal P '!wl-paste -n<ret>'"
# 		echo "map global normal R '|wl-paste -n<ret>'"
# 		echo "map global normal y '<a-|>wl-copy<ret><y>'"
# 		echo "map global normal d '<a-|>wl-copy<ret><d>'"
# 	fi
# }

hook global WinSetOption filetype=(c|cpp) %{
	set-option window clang_options '-std=c++26'
	set-option window formatcmd '$CF -style=file'
	set-option window tabstop 4
	# clang-enable-autocomplete
	# clang-enable-diagnostics
	# alias window lint clang-parse
	# alias window lint-next-error clang-diagnostics-next
	set-option buffer matching_pairs '{' '}' '[' ']' '(' ')'

	try %{
		add-highlighter -override buffer/operators regex (\W) 0:operator
		# add-highlighter -override buffer/operators regex (\+|-|\*|&|=|\\|\?|%|\|-|!|\||->|\.|,|<|>|:|\^|/|~|\[|\]) 0:operator
	}
}

hook global WinSetOption filetype=(python) %{
	set-option window indentwidth 4
	set-option window tabstop 4

	try %{
		add-highlighter -override buffer/operators regex (\W) 0:operator
	}
}

hook global WinSetOption filetype=(sql) %{
	try %{
		add-highlighter -override buffer/operators regex (\W) 0:operator
	}
}

hook global WinSetOption filetype=(markdown) %{
	try %{
		add-highlighter window/ wrap -word -indent
	}
}

hook global ModuleLoaded c-family %{ try %{ evaluate-commands %sh{
	for filetype in c cpp; do
		printf "%s\n" "add-highlighter shared/$filetype/code/types_1 regex \b(v|u|vu)\w+(8|16|32|64)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_2 regex \b(v|u|vu)?(_|__)?(s|u)(8|16|32|64)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_3 regex \b(v|u|vu)(_|__)?(int|short|char|long)(_t)?\b 0:type
		add-highlighter shared/$filetype/code/types_4 regex \b\w+_t\b 0:type"
	done
}}}

define-command -docstring 'Open a file' -params 0 open-file %{
evaluate-commands %sh{
		CMD="kak-open $kak_command_fifo"
		if [ -n "${TMUX+x}" ]; then
			tmux display-popup -d '#{pane_current_path}' -w 60% -h 50% -E ${CMD} >/dev/null 2>&1
		elif [ -n "${WAYLAND_DISPLAY+x}" ]; then
			foot --app-id=file-open --title=file-open ${CMD} >/dev/null 2>&1
		elif [ -n "${DISPLAY+x}" ]; then
			zutty -e ${CMD} >/dev/null 2>&1
		fi
	}
}

map global user 'e' ':open-file<ret>' -docstring 'Edit a file'
map global user 'd' ':db<ret>' -docstring 'Close buffer'
map global user 'n' ':bn<ret>' -docstring 'Next buffer'
map global user 'p' ':bp<ret>' -docstring 'Prev buffer'

source ~/.config/kak/rc/clipb.kak
