#!/bin/sh

doas /usr/local/etc/rc.d/tor onestart

VER=`pkg info chromium | grep Version | awk '{ print $3 }' | awk '{ split($1, a, "_"); print a[1] }'`
#UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$VER Safari/537.36"

flock -x -n /tmp/single-chromium.lock -c "proxychains chrome --incognito --force-gpu-rasterization --enable-native-gpu-memory-buffers --enable-gpu-rasterization --disk-cache-size=0 --disk-cache-dir=/dev/null --user-agent=\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$VER Safari/537.36\""

doas /usr/local/etc/rc.d/tor onestop
