#!/bin/sh

# Nvidia
# if (xrandr | grep "LVDS-0"); then
# 	INTERNAL="LVDS-0"
# 	EXTERNAL="HDMI-0"
# fi

# Intel
if (xrandr | grep "eDP-1"); then
	INTERNAL="eDP-1"
	EXTERNAL="DP-1"
fi

if (xrandr | grep "$EXTERNAL disconnected" > /dev/null); then
	xrandr --output $EXTERNAL --off --output $INTERNAL --auto
	#xrandr --dpi 160
else
	xrandr --output $INTERNAL --off --output $EXTERNAL --auto
	#xrandr --dpi 96
fi
