#!/bin/sh

TPID=`xinput list | grep '↳ Mouse' | gsed 's/.*id\=\([0-9]\+\).*/\1/g'`
STATUS=`xinput list-props $TPID | grep 'Device Enabled' | gsed -e 's/.*\:[ \t]\+//g'`

if [ $STATUS == 0 ]; then
	xinput enable $TPID
else
	xinput disable $TPID
fi
