#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
#bspc config top_padding 0
bspc config window_gap 12
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
#bspc config focus_by_distance true
#bspc config auto_cancel true
#bspc config honor_size_hints true
bspc config automatic_scheme alternate

bspc desktop --layout monocle

bspc config focused_border_color \#2379C2
bspc config normal_border_color none
bspc config presel_border_color none

#bspc rule -a Chrome fullscreen=on center=on desktop='^1'
#bspc rule -a urxvt fullscreen=on center=on desktop='^2'
#bspc rule -a mpv state=floating center=on desktop='^3'

sxhkd &
~/.bin/stmux
