verbosity = 2

[editor]
hover = false
zero_char_completion = false

[server]
ip = "127.0.0.1"
port = 31337

[language.rust]
extensions = ["rs"]
roots = ["Cargo.toml"]
command = "rls"

[language.javascript]
extensions = ["js", "jsx"]
roots = ["package.json"]
command = "flow-language-server"
args = ["--stdio"]

[language.json]
extensions = ["json"]
roots = ["package.json"]
command = "json-languageserver"
args = ["--stdio"]

[language.css]
extensions = ["css"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]

[language.html]
extensions = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]

[language.ocaml]
extensions = ["ml", "mli"]
roots = ["Makefile", "opam", "*.opam"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.reason]
extensions = ["re", "rei"]
roots = ["package.json", "Makefile", ".git"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.python]
extensions = ["py"]
roots = ["requirements.txt", "setup.py", ".git"]
command = "pyls"

[language.c_cpp]
extensions = ["c", "h", "cc", "hh", "cpp", "hpp"]
roots = ["compile_commands.json", ".cquery"]
command = "cquery"
args = ["--init={\"cacheDirectory\":\"/tmp/cquery\"}"]

[language.haskell]
extensions = ["hs"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "hie"
args = ["--lsp"]
